django/config/urls.py
from django.contrib import admin
from django.urls import path, include

import user.urls
import qanda.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(user.urls, namespace='user')),  
    path('', include(qanda.urls, namespace='qanda')),
]

django/qanda/urls.py
from django.urls.conf import path

from qanda import views

app_name = 'qanda'
urlpatterns = [
    path('ask/', views.AskQuestionView.as_view(), name='ask'),
    path('q/<int:pk>', views.QuestionDetailView.as_view(), name='question_detail'),
    path('q/<int:pk>/answer', views.CreateAnswerView.as_view(), name='answer_question'),
    path('a/<int:pk>/accept', views.UpdateAnswerAcceptanceView.as_view(),
        name='update_answer_acceptance'),
    path('daily/<int:year>/<int:month>/<int:day>/', views.DailyQuestionList.as_view(),
        name='daily_questions'),
    path('', views.TodaysQuestionList.as_view(), name='index'),
    path('q/search', views.SearchView.as_view(), name='question_search'),
]

django/user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
#from django.contrib.auth import urls

from user import views

app_name = 'user'
urlpatterns = [
    path('register', views.RegisterView.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    #path('', include(urls))
]

django/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}Answerly{% endblock %}</title>
  <link
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb"
      crossorigin="anonymous">
  <link
      href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      rel="stylesheet"
      integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
      crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'base.css' %}">
</head>

<body>
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container">
    <a class="navbar-brand" href="/">Answerly</a>
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'qanda:ask' %}">Ask</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'qanda:index' %}">
          Today's Questions
        </a>
      </li>
      {% if request.user.is_authenticated %}
        <a class="nav-link" href="{% url 'user:logout' %}">
          Log out
        </a>
      {% else %}
        <a class="nav-link" href="{% url 'user:login' %}">
          Log in
        </a>
        <a class="nav-link" href="{% url 'user:register' %}">
          Register
        </a>
      {% endif %}
      <li class="nav-item">
        <form class="form-inline"
              action="{% url 'qanda:question_search' %}"
              method="get">
          <input class="form-control mr-sm-2" type="search"
                 name="q"
                 placeholder="Search">
          <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">
            Search
          </button>
        </form>
      </li>
    </ul>
  </div>
</nav>
<div class="container">
  {% block body %}{% endblock %}
</div>
</body>
</html>